create mocha.opts
so that proper tests will show 0 passing (3s)                                                                                                             
  1 failing                                                                                                                  
                                                                                                                             
  1) loops "before all" hook:                                                                                                
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.                             
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)                                                                
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:320:18)                                                           
      at _combinedTickCallback (internal/process/next_tick.js:67:7)                                                          
      at process._tickCallback (internal/process/next_tick.js:98:9)